# Generated by Django 2.2.4 on 2019-10-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191013_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashbord',
            old_name='name',
            new_name='n',
        ),
    ]
