# Generated by Django 2.2.4 on 2019-10-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191013_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashbord',
            old_name='n',
            new_name='name',
        ),
    ]
