# Generated by Django 2.2.4 on 2019-10-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dd1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dd1',
            name='single',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dd1',
            name='team',
            field=models.CharField(default='', max_length=20),
        ),
    ]
