# Generated by Django 2.2.4 on 2019-10-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191015_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dd1',
            name='single',
        ),
    ]
