# Generated by Django 2.2.4 on 2019-10-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_dd1_single'),
    ]

    operations = [
        migrations.CreateModel(
            name='multiplayer1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dd1')),
            ],
        ),
        migrations.CreateModel(
            name='single2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.multiplayer1')),
            ],
        ),
        migrations.CreateModel(
            name='single1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dd1')),
            ],
        ),
    ]
