# Generated by Django 2.2.4 on 2019-10-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_multiplayer1_single1_single2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single2',
            name='team2',
        ),
        migrations.AlterField(
            model_name='dd1',
            name='team',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.DeleteModel(
            name='multiplayer1',
        ),
        migrations.DeleteModel(
            name='single2',
        ),
    ]
