# Generated by Django 2.2.4 on 2019-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191019_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dd1',
            name='team',
            field=models.CharField(default=' ', max_length=20, null=True),
        ),
    ]
